# Generated by Django 4.2.2 on 2023-06-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='center',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('reg_date', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('car_des', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=20)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.owner')),
            ],
        ),
        migrations.CreateModel(
            name='inspection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('insp_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.registration')),
            ],
        ),
    ]
